project:
  type: website
  output-dir: docs

website:
  title: "Claude Code Demo"
  description: "Interactive presentation on Claude Code and dialogue engineering"
  site-url: "https://la3d.github.io/cc-demo"
  repo-url: "https://github.com/LA3D/cc-demo"
  repo-actions: [edit, issue]
  
  navbar:
    background: dark
    search: false
    
  page-footer:
    left: "Built with [Quarto](https://quarto.org/) and [RevealJS](https://revealjs.com/)"
    right: "© 2024"

format:
  revealjs:
    theme: [default, styles.css]
    slide-number: true
    chalkboard: true
    preview-links: auto
    logo: ""
    footer: "Claude Code Demo - Dialogue Engineering"
    transition: slide
    background-transition: fade
    highlight-style: github-dark
    code-line-numbers: true
    code-overflow: wrap
    fig-cap-location: bottom
    tbl-cap-location: top
    embed-resources: false

execute:
  freeze: auto
  echo: true
  warning: false
  error: false